package main

import (
	"math"
	"strconv"
	"time"
	"fmt"
	"encoding/json"
)


const text = `
{ "data": {
	"age": 27,
	"avatarPhotoID": 108453341,
	"avatarPraiseCount": 0,
	"avatarPraised": false,
	"avatarURL": "https://photo.zastatic.com/images/photo/16107/64426003/1454920466430.jpg",
	"basicInfo": [
		"未婚",
		"27岁",
		"射手座(11.22-12.21)",
		"165cm",
		"70kg",
		"工作地:昌都察雅",
		"月收入:1.2-2万",
		"工程师",
		"大专"
	],
	"detailInfo": [
		"汉族",
		"籍贯:重庆",
		"体型:体格魁梧",
		"稍微抽一点烟",
		"不喝酒",
		"已购房",
		"已买车",
		"有孩子但不在身边",
		"是否想要孩子:想要孩子",
		"何时结婚:时机成熟就结婚"
	],
	"educationString": "大专",
	"emotionStatus": 0,
	"gender": 0,
	"genderString": "男士",
	"hasIntroduce": true,
	"heightString": "165cm",
	"hideVerifyModule": false,
	"introduceContent": "我只是一个老实人，请不要骗我，寻找一个互相体贴，互相理解。谢谢，还有这个，我离异，资料改不了",
	"introducePraiseCount": 0,
	"isActive": false,
	"isFollowing": false,
	"isInBlackList": false,
	"isStar": false,
	"isZhenaiMail": false,
	"lastLoginTimeString": "4天前活跃",
	"liveAudienceCount": 0,
	"liveType": 0,
	"marriageString": "未婚",
	"memberID": 64426003,
	"momentCount": 3,
	"nickname": "张韶勇",
	"objectAgeString": "18-23岁",
	"objectBodyString": "一般",
	"objectChildrenString": "没有小孩",
	"objectEducationString": "未填写",
	"objectHeightString": "157-168cm",
	"objectInfo": [
		"18-23岁",
		"157-168cm",
		"体型:一般",
		"可以喝酒",
		"不要吸烟",
		"没有小孩",
		"是否想要孩子:想要孩子"
	],
	"objectMarriageString": "未填写",
	"objectSalaryString": "未填写",
	"objectWantChildrenString": "想要孩子",
	"objectWorkCityString": "未填写",
	"onlive": 0,
	"photoCount": 13,
	"photos": [
		{
		"createTime": "2016-02-08 16:31:32",
		"isAvatar": true,
		"photoID": 108453341,
		"photoType": 1,
		"photoURL": "https://photo.zastatic.com/images/photo/16107/64426003/1454920466430.jpg",
		"praiseCount": 0,
		"praised": false,
		"verified": true
		},
		{
		"createTime": "2016-02-08 16:33:30",
		"isAvatar": false,
		"photoID": 108453390,
		"photoType": 1,
		"photoURL": "https://photo.zastatic.com/images/photo/16107/64426003/1454920407967.jpg",
		"praiseCount": 0,
		"praised": false,
		"verified": true
		},
		{
		"createTime": "2016-02-08 16:32:17",
		"isAvatar": false,
		"photoID": 108453359,
		"photoType": 1,
		"photoURL": "https://photo.zastatic.com/images/photo/16107/64426003/1454920334896.jpg",
		"praiseCount": 0,
		"praised": false,
		"verified": true
		},
		{
		"createTime": "2014-08-28 22:54:24",
		"isAvatar": false,
		"photoID": 88690599,
		"photoType": 1,
		"photoURL": "https://photo.zastatic.com/images/photo/16107/64426003/1409237662333.jpg",
		"praiseCount": 0,
		"praised": false,
		"verified": true
		},
		{
		"createTime": "2014-08-28 22:52:42",
		"isAvatar": false,
		"photoID": 88690541,
		"photoType": 1,
		"photoURL": "https://photo.zastatic.com/images/photo/16107/64426003/1409237560339.jpg",
		"praiseCount": 0,
		"praised": false,
		"verified": true
		},
		{
		"createTime": "2014-08-24 22:20:24",
		"isAvatar": false,
		"photoID": 88563554,
		"photoType": 1,
		"photoURL": "https://photo.zastatic.com/images/photo/16107/64426003/1408890021910.jpg",
		"praiseCount": 0,
		"praised": false,
		"verified": true
		},
		{
		"createTime": "2014-02-23 18:08:39",
		"isAvatar": false,
		"photoID": 81162114,
		"photoType": 1,
		"photoURL": "https://photo.zastatic.com/images/photo/16107/64426003/1393150117993.jpg",
		"praiseCount": 0,
		"praised": false,
		"verified": true
		},
		{
		"createTime": "2014-02-23 18:08:37",
		"isAvatar": false,
		"photoID": 81162112,
		"photoType": 1,
		"photoURL": "https://photo.zastatic.com/images/photo/16107/64426003/1393150115864.jpg",
		"praiseCount": 0,
		"praised": false,
		"verified": true
		},
		{
		"createTime": "2014-02-23 18:08:27",
		"isAvatar": false,
		"photoID": 81162102,
		"photoType": 1,
		"photoURL": "https://photo.zastatic.com/images/photo/16107/64426003/1393150105924.jpg",
		"praiseCount": 0,
		"praised": false,
		"verified": true
		}
	],
	"praisedIntroduce": false,
	"previewPhotoURL": "",
	"pycreditCertify": false,
	"salaryString": "12001-20000元",
	"showValidateIDCardFlag": false,
	"superRecClickTip": "点击可进行超级推荐",
	"superRecGuideTip": "该用户是超级推荐的用户",
	"superRecommend": false,
	"totalPhotoCount": 13,
	"validateEducation": false,
	"validateFace": false,
	"validateIDCard": true,
	"videoCount": 0,
	"videoID": 0,
	"workCity": 10128033,
	"workCityString": "昌都",
	"workProvinceCityString": "昌都察雅"
	},
	"errorCode": "",
	"errorMessage": "",
	"isError": false
}`


// AutoGenerated type
type AutoGenerated struct {
	Data struct {
		Age                      int      `json:"age"`
		BasicInfo                []string `json:"basicInfo"`
		DetailInfo               []string `json:"detailInfo"`
		EducationString          string   `json:"educationString"`
		EmotionStatus            int      `json:"emotionStatus"`
		Gender                   int      `json:"gender"`
		GenderString             string   `json:"genderString"`
		Nickname                 string   `json:"nickname"`
	} `json:"data"`

}


func main() {
	a := AutoGenerated{}
	err := json.Unmarshal([]byte(text), &a)
	if err != nil {
		panic(err)
	}
	fmt.Println(a.Data)
	fmt.Println(strconv.FormatInt(time.Now().UnixNano() / int64(math.Pow(10, 6)), 10))
}

